In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('breast-cancer.data',na_values=['?'])
df.columns=['class','age','menopause','tumor_size','inv_nodes','node_caps','deg-malig','breast','breaset-quad','target']
df.replace({'?':np.nan})

class    age menopause tumor_size inv_nodes node_caps  \
0    no-recurrence-events  40-49   premeno      20-24       0-2        no   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  60-69      ge40      15-19       0-2        no   
3    no-recurrence-events  40-49   premeno        0-4       0-2        no   
4    no-recurrence-events  60-69      ge40      15-19       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
280     recurrence-events  30-39   premeno      30-34       0-2        no   
281     recurrence-events  30-39   premeno      20-24       0-2        no   
282     recurrence-events  60-69      ge40      20-24       0-2        no   
283     recurrence-events  40-49      ge40      30-34       3-5        no   
284     recurrence-events  50-59      ge40      30-34       3-5        no   

     deg-malig breast breaset-quad target  
0            2  right     right_up     no  
1            2   left     left_low     no  
2            2  right      left_up     no  
3            2  right    right_low     no  
4            2   left     left_low     no  
..         ...    ...          ...    ...  
280          2   left      left_up     no  
281          3   left      left_up    yes  
282          1  right      left_up     no  
283          3   left     left_low     no  
284          3   left     left_low     no  

[285 rows x 10 columns]

In [3]:
labelencoder=LabelEncoder()
df['target'] = labelencoder.fit_transform(df['target'])

In [4]:
df.isna().any()

class           False
age             False
menopause       False
tumor_size      False
inv_nodes       False
node_caps        True
deg-malig       False
breast          False
breaset-quad     True
target          False
dtype: bool

In [5]:
df.node_caps.isnull().sum()

8

In [6]:
df['breaset-quad'].isnull().sum()

1

In [7]:
for column in ['breaset-quad','node_caps']:
    df[column]=df[column].fillna(df[column].mode()[0])
    print(df[column].mode()[0])
    

left_low
no


In [8]:
#LabelEncoding
need_le=['age','tumor_size','inv_nodes']
labelencoder=LabelEncoder()
for col in need_le:
    df[col]=labelencoder.fit_transform(df[col])
df

class  age menopause  tumor_size  inv_nodes node_caps  \
0    no-recurrence-events    2   premeno           3          0        no   
1    no-recurrence-events    2   premeno           3          0        no   
2    no-recurrence-events    4      ge40           2          0        no   
3    no-recurrence-events    2   premeno           0          0        no   
4    no-recurrence-events    4      ge40           2          0        no   
..                    ...  ...       ...         ...        ...       ...   
280     recurrence-events    1   premeno           5          0        no   
281     recurrence-events    1   premeno           3          0        no   
282     recurrence-events    4      ge40           3          0        no   
283     recurrence-events    2      ge40           5          4        no   
284     recurrence-events    3      ge40           5          4        no   

     deg-malig breast breaset-quad  target  
0            2  right     right_up       0  
1            2   left     left_low       0  
2            2  right      left_up       0  
3            2  right    right_low       0  
4            2   left     left_low       0  
..         ...    ...          ...     ...  
280          2   left      left_up       0  
281          3   left      left_up       1  
282          1  right      left_up       0  
283          3   left     left_low       0  
284          3   left     left_low       0  

[285 rows x 10 columns]

In [9]:

df=pd.get_dummies(df)
df

age  tumor_size  inv_nodes  deg-malig  target  \
0      2           3          0          2       0   
1      2           3          0          2       0   
2      4           2          0          2       0   
3      2           0          0          2       0   
4      4           2          0          2       0   
..   ...         ...        ...        ...     ...   
280    1           5          0          2       0   
281    1           3          0          3       1   
282    4           3          0          1       0   
283    2           5          4          3       0   
284    3           5          4          3       0   

     class_no-recurrence-events  class_recurrence-events  menopause_ge40  \
0                             1                        0               0   
1                             1                        0               0   
2                             1                        0               1   
3                             1                        0               0   
4                             1                        0               1   
..                          ...                      ...             ...   
280                           0                        1               0   
281                           0                        1               0   
282                           0                        1               1   
283                           0                        1               1   
284                           0                        1               1   

     menopause_lt40  menopause_premeno  node_caps_no  node_caps_yes  \
0                 0                  1             1              0   
1                 0                  1             1              0   
2                 0                  0             1              0   
3                 0                  1             1              0   
4                 0                  0             1              0   
..              ...                ...           ...            ...   
280               0                  1             1              0   
281               0                  1             1              0   
282               0                  0             1              0   
283               0                  0             1              0   
284               0                  0             1              0   

     breast_left  breast_right  breaset-quad_central  breaset-quad_left_low  \
0              0             1                     0                      0   
1              1             0                     0                      1   
2              0             1                     0                      0   
3              0             1                     0                      0   
4              1             0                     0                      1   
..           ...           ...                   ...                    ...   
280            1             0                     0                      0   
281            1             0                     0                      0   
282            0             1                     0                      0   
283            1             0                     0                      1   
284            1             0                     0                      1   

     breaset-quad_left_up  breaset-quad_right_low  breaset-quad_right_up  
0                       0                       0                      1  
1                       0                       0                      0  
2                       1                       0                      0  
3                       0                       1                      0  
4                       0                       0                      0  
..                    ...                     ...                    ...  
280                     1                       0                      0  
281                     1                

In [10]:
df=df.drop(['class_no-recurrence-events','menopause_ge40','node_caps_no','breast_left','breaset-quad_central'],axis=1)

In [11]:
df.corr()

age  tumor_size  inv_nodes  deg-malig    target  \
age                      1.000000   -0.013599  -0.046375  -0.079114 -0.045551   
tumor_size              -0.013599    1.000000   0.150730   0.162318  0.160565   
inv_nodes               -0.046375    0.150730   1.000000   0.285872  0.381977   
deg-malig               -0.079114    0.162318   0.285872   1.000000  0.211362   
target                  -0.045551    0.160565   0.381977   0.211362  1.000000   
class_recurrence-events -0.075897    0.131710   0.291194   0.303457  0.192887   
menopause_lt40           0.051974   -0.078191  -0.088370  -0.071429 -0.088828   
menopause_premeno       -0.717536    0.006900  -0.005454  -0.036233  0.056847   
node_caps_yes           -0.057262    0.166962   0.623974   0.329268  0.303283   
breast_right            -0.047497    0.032714   0.020557  -0.048827  0.016957   
breaset-quad_left_low    0.023482   -0.018640   0.042884  -0.009964  0.029667   
breaset-quad_left_up     0.051425    0.021398  -0.005696   0.056092  0.032248   
breaset-quad_right_low  -0.088888   -0.084792  -0.018634  -0.035958  0.037757   
breaset-quad_right_up   -0.033930    0.178636   0.013905   0.022269 -0.048206   

                         class_recurrence-events  menopause_lt40  \
age                                    -0.075897        0.051974   
tumor_size                              0.131710       -0.078191   
inv_nodes                               0.291194       -0.088370   
deg-malig                               0.303457       -0.071429   
target                                  0.192887       -0.088828   
class_recurrence-events                 1.000000       -0.004347   
menopause_lt40                         -0.004347        1.000000   
menopause_premeno                       0.054686       -0.166093   
node_caps_yes                           0.275989       -0.078470   
breast_right                           -0.060927       -0.058646   
breaset-quad_left_low                   0.050304        0.013888   
breaset-quad_left_up                   -0.047424        0.029544   
breaset-quad_right_low                 -0.031979       -0.048118   
breaset-quad_right_up                   0.075694        0.013423   

                         menopause_premeno  node_caps_yes  breast_right  \
age                              -0.717536      -0.057262     -0.047497   
tumor_size                        0.006900       0.166962      0.032714   
inv_nodes                        -0.005454       0.623974      0.020557   
deg-malig                        -0.036233       0.329268     -0.048827   
target                            0.056847       0.303283      0.016957   
class_recurrence-events           0.054686       0.275989     -0.060927   
menopause_lt40                   -0.166093      -0.078470     -0.058646   
menopause_premeno                 1.000000       0.048138      0.069584   
node_caps_yes                     0.048138       1.000000     -0.005835   
breast_right                      0.069584      -0.005835      1.000000   
breaset-quad_left_low            -0.007342      -0.011138     -0.284761   
breaset-quad_left_up             -0.055037      -0.019748      0.228382   
breaset-quad_right_low            0.087339       0.009037     -0.108455   
breaset-quad_right_up             0.060317       0.069430      0.186405   

                         breaset-quad_left_low  breaset-quad_left_up  \
age                                   0.023482              0.051425   
tumor_size                           -0.018640              0.021398   
inv_nodes                             0.042884             -0.005696   
deg-malig                            -0.009964              0.056092   
target                                0.029667              0.032248   
class_recurrence-events               0.050304             -0.047424   
menopause_lt40                        0.013888              0.029544   
menopause_premeno                    -0.007342             -0.055037   
node_caps_yes      

In [12]:
y=df['target']
X=df.drop(['target','age'],axis =1)
df.shape

(285, 14)

In [13]:
from sklearn import preprocessing
sc=preprocessing.StandardScaler()
sc.fit_transform(X)

array([[-0.49275282, -0.55689829, -0.06197084, ..., -0.71830178,
        -0.30323922,  2.76339712],
       [-0.49275282, -0.55689829, -0.06197084, ..., -0.71830178,
        -0.30323922, -0.36187343],
       [-0.9577679 , -0.55689829, -0.06197084, ...,  1.39217252,
        -0.30323922, -0.36187343],
       ...,
       [-0.49275282, -0.55689829, -1.4205624 , ...,  1.39217252,
        -0.30323922, -0.36187343],
       [ 0.43727734,  1.51106278,  1.29662072, ..., -0.71830178,
        -0.30323922, -0.36187343],
       [ 0.43727734,  1.51106278,  1.29662072, ..., -0.71830178,
        -0.30323922, -0.36187343]])

In [14]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = LogisticRegression()

results = model_selection.cross_val_score(model, X, y, cv=kfold)
#print(cross_validate(model, X, y,scoring=scoring))
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 76.515% (21.257%)


In [15]:
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = DecisionTreeClassifier()
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 69.914% (17.127%)


In [16]:
from sklearn import model_selection
from sklearn.neighbors import KNeighborsClassifier
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = KNeighborsClassifier()
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 73.091% (19.563%)


In [17]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = RandomForestClassifier()
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 71.626% (22.185%)


In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0)

In [19]:
model =tf.keras.models.Sequential([
          tf.keras.layers.Dense(256,activation='relu',input_shape=(12,)),
          tf.keras.layers.Dropout(0.2),
          tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy','Precision','Recall'])
class_weight = { 0: 0.30,
                 1: 0.70}
model.fit(X_train, y_train, epochs = 10,batch_size=64,verbose=2)

Train on 228 samples
Epoch 1/10
228/228 - 0s - loss: 0.6624 - accuracy: 0.6404 - Precision: 0.2340 - Recall: 0.1930
Epoch 2/10
228/228 - 0s - loss: 0.6364 - accuracy: 0.7412 - Precision: 0.2500 - Recall: 0.0175
Epoch 3/10
228/228 - 0s - loss: 0.5898 - accuracy: 0.7588 - Precision: 1.0000 - Recall: 0.0351
Epoch 4/10
228/228 - 0s - loss: 0.5812 - accuracy: 0.7544 - Precision: 0.6667 - Recall: 0.0351
Epoch 5/10
228/228 - 0s - loss: 0.5579 - accuracy: 0.7632 - Precision: 0.6364 - Recall: 0.1228
Epoch 6/10
228/228 - 0s - loss: 0.5437 - accuracy: 0.7588 - Precision: 0.5312 - Recall: 0.2982
Epoch 7/10
228/228 - 0s - loss: 0.5446 - accuracy: 0.7632 - Precision: 0.5385 - Recall: 0.3684
Epoch 8/10
228/228 - 0s - loss: 0.5328 - accuracy: 0.7807 - Precision: 0.6129 - Recall: 0.3333
Epoch 9/10
228/228 - 0s - loss: 0.5333 - accuracy: 0.7763 - Precision: 0.5882 - Recall: 0.3509
Epoch 10/10
228/228 - 0s - loss: 0.5286 - accuracy: 0.7895 - Precision: 0.6452 - Recall: 0.3509


In [20]:
y_pred= model.evaluate(X_test,y_test)


57/57 [==============================] - 0s 2ms/sample - loss: 0.4633 - accuracy: 0.8596 - Precision: 0.7143 - Recall: 0.4545


In [21]:
def f1_score(p,r):
    return 2*(p*r)/(p+r)
print('F1 Score::',f1_score(y_pred[-2],y_pred[-1]))

F1 Score:: 0.5555555725539163


In [22]:

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
     

[[35 11]
 [ 5  6]]
              precision    recall  f1-score   support

           0       0.88      0.76      0.81        46
           1       0.35      0.55      0.43        11

    accuracy                           0.72        57
   macro avg       0.61      0.65      0.62        57
weighted avg       0.77      0.72      0.74        57

Accuracy :  71.9298245614035


In [23]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier()
clf1.fit(X_train,y_train)
y_pred1=clf1.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[35 11]
 [ 5  6]]
              precision    recall  f1-score   support

           0       0.88      0.76      0.81        46
           1       0.35      0.55      0.43        11

    accuracy                           0.72        57
   macro avg       0.61      0.65      0.62        57
weighted avg       0.77      0.72      0.74        57

Accuracy :  71.9298245614035


In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[41  5]
 [ 8  3]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86        46
           1       0.38      0.27      0.32        11

    accuracy                           0.77        57
   macro avg       0.61      0.58      0.59        57
weighted avg       0.75      0.77      0.76        57

Accuracy :  77.19298245614034
